services:
#  app:
#    build: .
#    ports:
#      - '3000:3000'
#    volumes:
#      - .:/app
#      - /app/node_modules
#    environment:
#      DATABASE_URL: postgres://postgres:postgres@db:5432/nestdb
#    depends_on:
#      - db
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: GvXWmzMLP03HNmrp
      POSTGRES_DB: nestdb
    ports:
      - '5432:5432'
