name: Deploy Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted  # Используем self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Backend
        run: |
          docker-compose -f docker-compose.yml down
          docker-compose -f docker-compose.yml build --no-cache
          docker-compose -f docker-compose.yml up -d
